---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/cqi/.aar_doc.yml
      - roles/cqi/README.md
      - roles/cqi/meta/argument_specs.yml
      - roles/cqi/meta/main.yml
      - roles/licensing/.aar_doc.yml
      - roles/licensing/README.md
      - roles/licensing/meta/argument_specs.yml
      - roles/licensing/meta/main.yml
      - roles/pvs_console/.aar_doc.yml
      - roles/pvs_console/README.md
      - roles/pvs_console/meta/argument_specs.yml
      - roles/pvs_console/meta/main.yml
      - roles/pvs_server/.aar_doc.yml
      - roles/pvs_server/README.md
      - roles/pvs_server/meta/argument_specs.yml
      - roles/pvs_server/meta/main.yml
      - roles/pvs_target/.aar_doc.yml
      - roles/pvs_target/README.md
      - roles/pvs_target/meta/argument_specs.yml
      - roles/pvs_target/meta/main.yml
      - roles/wem_agent/.aar_doc.yml
      - roles/wem_agent/README.md
      - roles/wem_agent/meta/argument_specs.yml
      - roles/wem_agent/meta/main.yml
      - roles/win_server_vda/.aar_doc.yml
      - roles/win_server_vda/README.md
      - roles/win_server_vda/meta/argument_specs.yml
      - roles/win_server_vda/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  docs_cqi:
    name: Generate cqi role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate cqi role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/cqi
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update cqi role documentation." || /bin/true
          git push origin main
          deactivate
  docs_licensing:
    name: Generate licensing role documentation
    needs: docs_cqi
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate licensing role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/licensing
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update licensing role documentation." || /bin/true
          git push origin main
          deactivate
  docs_pvs_console:
    name: Generate pvs_console role documentation
    needs: docs_licensing
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate pvs_console role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/pvs_console
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update pvs_console role documentation." || /bin/true
          git push origin main
          deactivate
  docs_pvs_server:
    name: Generate pvs_server role documentation
    needs: docs_pvs_console
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate pvs_server role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/pvs_server
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update pvs_server role documentation." || /bin/true
          git push origin main
          deactivate
  docs_pvs_target:
    name: Generate pvs_target role documentation
    needs: docs_pvs_server
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate pvs_target role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/pvs_target
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update pvs_target role documentation." || /bin/true
          git push origin main
          deactivate
  docs_wem_agent:
    name: Generate wem_agent role documentation
    needs: docs_pvs_target
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate wem_agent role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/wem_agent
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update wem_agent role documentation." || /bin/true
          git push origin main
          deactivate
  docs_win_server_vda:
    name: Generate win_server_vda role documentation
    needs: docs_wem_agent
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.citrix
          ref: main
      - name: Generate win_server_vda role documentation
        working-directory: 'trippsc2.citrix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/win_server_vda
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update win_server_vda role documentation." || /bin/true
          git push origin main
          deactivate
